{% set name = "combat_tb_model" %}
{% set version = "0.0.2" %}
{% set sha256 = "1156993d91cc5e3c7b34609d0b145b704b5459d4faebd87b01936d1669b815e7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://github.com/SANBI-SA/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - py2neo
  run:
    - python
    - py2neo
test:
  imports:
    - combat_tb_model.model.core
    - combat_tb_model.model.vcfmodel

about:
  home: https://github.com/SANBI-SA/combat_tb_model
  summary: 'COMBAT-TB Graph Model,a Chado-derived graph model for genome annotation.'
