{% set name = "combat_tb_model" %}
{% set version = "0.0.3" %}
{% set sha256 = "8d06e9d200af15f0c074c73b9e72a4652ea1f658e5a9538bd0400701a9153cc2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://github.com/SANBI-SA/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - py2neo
  run:
    - python
    - py2neo
test:
  imports:
    - combat_tb_model.model.core
    - combat_tb_model.model.vcfmodel
    - combat_tb_model.model.fasttree

about:
  home: https://github.com/SANBI-SA/combat_tb_model
  summary: 'COMBAT-TB Graph Model,a Chado-derived graph model for genome annotation.'
